Uninstall Fluent Bit when stopping a GitOps Run session
The Fluent Bit HelmRelease is not removed from the cluster as soon as
the GitOps Run session terminates. Prior to this you weren't able to
start another session after terminating the first one.

This commit introduces the `CleanupFunc` type that `fluentBitStep`
returns. This function is pushed onto a stack and at session
termination each function on that stack is popped and executed,
guaranteeing a cleanup of any resources created by GitOps Run itself.

We should gradually add the `CleanupFunc` type to the other steps,
too so that cleanup is done in a standardized manner.

Before:

```
$ gitops run --no-session ./kustomize/
► Checking for a cluster in the kube config ...
[...]
► Request reconciliation of GitOps Run resources (timeout 5m0s) ...
✔ Reconciliation is done.
^C► Received interrupt, quitting...
[...]
$ k get hr -A
NAMESPACE     NAME         AGE   READY   STATUS
flux-system   fluent-bit   62s   True    Release reconciliation succeeded
$ $ gitops run --no-session ./kustomize/
[...]
► waiting for HelmRelease flux-system/fluent-bit to be ready
✗ HelmRelease flux-system/fluent-bit failed to become ready
✗ Fluent Bit installation failed: timed out waiting for the condition
Error: timed out waiting for the condition
```

After:

```
$ gitops run --no-session ./kustomize/
► Checking for a cluster in the kube config ...
[...]
► Request reconciliation of GitOps Run resources (timeout 5m0s) ...
✔ Reconciliation is done.
^C► Received interrupt, quitting...
[...]
$ k get hr -A
No resources found
$ $ gitops run --no-session ./kustomize/
[...]
✔ Reconciliation is done.
```

closes #3375